# Generated by Django 6.0.4 on 2026-05-19 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название задачи')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Новичок'), (2, 'Исследователь'), (3, 'Эксперт')], verbose_name='Сложность')),
                ('story', models.TextField(verbose_name='Сюжет задачи')),
                ('theory', models.TextField(verbose_name='Предметная справка')),
                ('starter_code', models.TextField(verbose_name='Стартовый код')),
                ('tests', models.JSONField(verbose_name='Тесты')),
                ('hint', models.TextField(verbose_name='Подсказка')),
                ('easier_text', models.TextField(blank=True, verbose_name='Упрощенный вариант')),
                ('reward_points', models.PositiveSmallIntegerField(default=20, verbose_name='Баллы')),
                ('visual_kind', models.CharField(default='chart', max_length=40, verbose_name='Тип визуализации')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'квест',
                'verbose_name_plural': 'квесты',
                'ordering': ['world__order', 'difficulty', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название мира')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('subject', models.CharField(max_length=80, verbose_name='Предмет')),
                ('intro', models.TextField(verbose_name='Короткое описание')),
                ('color', models.CharField(default='#2f80ed', max_length=20, verbose_name='Основной цвет')),
                ('accent', models.CharField(default='#27ae60', max_length=20, verbose_name='Акцентный цвет')),
                ('icon', models.CharField(default='spark', max_length=40, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'научный мир',
                'verbose_name_plural': 'научные миры',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Сессия')),
                ('code', models.TextField(verbose_name='Код ученика')),
                ('is_success', models.BooleanField(default=False, verbose_name='Решено')),
                ('passed_tests', models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено тестов')),
                ('total_tests', models.PositiveSmallIntegerField(default=0, verbose_name='Всего тестов')),
                ('feedback', models.TextField(verbose_name='Комментарий проверки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.quest')),
            ],
            options={
                'verbose_name': 'отправка',
                'verbose_name_plural': 'отправки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='main.world'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Сессия')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('solved_count', models.PositiveSmallIntegerField(default=0, verbose_name='Решено задач')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='main.world')),
            ],
            options={
                'verbose_name': 'прогресс',
                'verbose_name_plural': 'прогресс',
                'unique_together': {('session_key', 'world')},
            },
        ),
    ]
