# Generated by Django 6.0.4 on 2026-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_worlds'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные задания'),
        ),
        migrations.AddField(
            model_name='quest',
            name='task_type',
            field=models.CharField(choices=[('python', 'Python'), ('quiz', 'Тест'), ('match', 'Сопоставление')], default='python', max_length=20, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='starter_code',
            field=models.TextField(blank=True, verbose_name='Стартовый код'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='tests',
            field=models.JSONField(blank=True, default=list, verbose_name='Тесты Python'),
        ),
    ]
