# Generated by Django 6.0.4 on 2026-05-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_richer_subject_quests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['world__order', 'lesson__order', 'step_order', 'difficulty', 'order', 'title'], 'verbose_name': 'квест', 'verbose_name_plural': 'квесты'},
        ),
        migrations.AddField(
            model_name='quest',
            name='step_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок шага в уроке'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название урока')),
                ('slug', models.SlugField(verbose_name='URL-адрес урока')),
                ('intro', models.TextField(verbose_name='Описание урока')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.world')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['world__order', 'order', 'title'],
                'unique_together': {('world', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.lesson', verbose_name='Урок'),
        ),
    ]
