# Generated by Django 5.0.14 on 2026-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_more_lesson_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='min_points_required',
            field=models.PositiveIntegerField(default=0, verbose_name='RP для открытия'),
        ),
    ]
