# Generated by Django 6.0.4 on 2026-05-19 07:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
                ('topic', models.CharField(max_length=80, verbose_name='Тема')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Легко'), (2, 'Средне'), (3, 'Сложно')], verbose_name='Сложность')),
                ('short_description', models.CharField(max_length=220, verbose_name='Короткое описание')),
                ('task_text', models.TextField(verbose_name='Условие')),
                ('starter_code', models.TextField(verbose_name='Стартовый код')),
                ('tests', models.JSONField(verbose_name='Тесты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['difficulty', 'topic', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Сессия ученика')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('is_success', models.BooleanField(default=False, verbose_name='Решено')),
                ('passed_tests', models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено тестов')),
                ('total_tests', models.PositiveSmallIntegerField(default=0, verbose_name='Всего тестов')),
                ('feedback', models.TextField(verbose_name='Обратная связь')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда отправлено')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.exercise')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
                'ordering': ['-created_at'],
            },
        ),
    ]
