# Generated by Django 6.0.4 on 2026-05-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_seed_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название курса')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['module__order', 'difficulty', 'topic', 'title'], 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название модуля')),
                ('slug', models.SlugField(verbose_name='Адрес модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lessons.course')),
            ],
            options={
                'verbose_name': 'модуль курса',
                'verbose_name_plural': 'модули курсов',
                'ordering': ['course__title', 'order', 'title'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='lessons.coursemodule', verbose_name='Модуль'),
        ),
    ]
